name: pgadmin4 container pre-publish

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: The branch, tag or SHA to checkout. Defaults to the reference or SHA for that event.
        required: false
        type: string
      dockerfile-dir:
        description: Dockerfile directory
        required: false
        type: string
    outputs:
      container-image-name:
        value: ${{ jobs.pgadmin4-pre-publish.outputs.container-image-name }}
      pgadmin4-version:
        value: ${{ jobs.pgadmin4-pre-publish.outputs.pgadmin4-version }}

jobs:
  pgadmin4-pre-publish:
    runs-on: ubuntu-latest
    outputs:
      container-image-name: ${{ steps.container-image-name.outputs.VALUE }}
      pgadmin4-version: ${{ steps.pgadmin4-version.outputs.VERSION }}
    steps:
      - name: Compose container image name
        id: container-image-name
        run: echo "VALUE=${REPO_NAME#container-}" >>$GITHUB_OUTPUT
        env:
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: Find out embedded pgadmin4 version
        id: pgadmin4-version
        run: echo "VERSION=$(scripts/pgadmin4-version.sh "${{ inputs.dockerfile-dir }}")" >>$GITHUB_OUTPUT
