name: Validate & publish (branch)

on:
  push:
    branches: [ main ]

jobs:
  validate:
    uses: anthochamp/dev-toolbox/.github/workflows/container-validate.yml@b9a37d6321d8353e62b17d37812367f4caaa57cf

  get-version:
    needs: validate
    uses: anthochamp/dev-toolbox/.github/workflows/util-get-latest-git-version-tag.yml@b9a37d6321d8353e62b17d37812367f4caaa57cf

  pre-publish:
    needs: validate
    uses: ./.github/workflows/pgadmin4-pre-publish.yml
    with:
      dockerfile-dir: src

  publish:
    needs: [validate, get-version, pre-publish]
    permissions:
      packages: write
      id-token: write # used for sigstore/fulcio identity challenge
    uses: anthochamp/dev-toolbox/.github/workflows/container-publish.yml@b9a37d6321d8353e62b17d37812367f4caaa57cf
    with:
      dockerfile-dir: src
      dhub-readme-file: ./CONTAINER.md
      version: ${{ needs.get-version.outputs.version }}
      alt-version: ${{ needs.pre-publish.outputs.pgadmin4-version }}
      alt-version-prefix: pgadmin4
      container-image-name: ${{ needs.pre-publish.outputs.container-image-name }}
      # https://hub.docker.com/r/dpage/pgadmin4/tags
      build-platforms: linux/amd64,linux/arm64
    secrets:
      dhub-username: ${{ secrets.DHUB_USERNAME }}
      dhub-password: ${{ secrets.DHUB_PASSWORD }}
      ghcr-username: ${{ github.repository_owner }}
      ghcr-password: ${{ secrets.GITHUB_TOKEN }}
