name: Validate & publish (schedule)

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  get-version-tag:
    uses: anthochamp/dev-toolbox/.github/workflows/util-get-latest-git-version-tag.yml@29286f8eb85cc4f61525c18a874713a4867a37e0

  validate:
    needs: get-version-tag
    uses: anthochamp/dev-toolbox/.github/workflows/container-validate.yml@29286f8eb85cc4f61525c18a874713a4867a37e0
    with:
      checkout-ref: ${{ needs.get-version-tag.outputs.tag }}

  pre-publish:
    needs: [validate, get-version-tag]
    uses: ./.github/workflows/pgadmin4-pre-publish.yml
    with:
      checkout-ref: ${{ needs.get-version-tag.outputs.tag }}
      dockerfile-dir: src

  publish:
    needs: [validate, get-version-tag, pre-publish]
    permissions:
      packages: write
      id-token: write # used for sigstore/fulcio identity challenge
    uses: anthochamp/dev-toolbox/.github/workflows/container-publish.yml@29286f8eb85cc4f61525c18a874713a4867a37e0
    with:
      checkout-ref: ${{ needs.get-version-tag.outputs.tag }}
      dockerfile-dir: src
      dhub-readme-file: ./CONTAINER.md
      version: ${{ needs.get-version-tag.outputs.version }}
      alt-version: ${{ needs.pre-publish.outputs.pgadmin4-version }}
      alt-version-prefix: pgadmin4
      container-image-name: ${{ needs.pre-publish.outputs.container-image-name }}
      # https://hub.docker.com/r/dpage/pgadmin4/tags
      build-platforms: linux/amd64,linux/arm64
    secrets:
      dhub-username: ${{ secrets.DHUB_USERNAME }}
      dhub-password: ${{ secrets.DHUB_PASSWORD }}
      ghcr-username: ${{ github.repository_owner }}
      ghcr-password: ${{ secrets.GITHUB_TOKEN }}
